---
title: "Reading data from the web"
author: "Yifan Su"
date: "10/19/2020"
output: github_document
---

```{r eval=FALSE}
library(tidyverse)

library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Scrape a table

I want the first table from [this page](http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm)

read in the html

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)

drug_use_html
```

extract the tables; focus on the first one

```{r}
table_marj =
drug_use_html %>%
  html_nodes(css = "table") %>% 
  first() %>% # select the first table
  html_table() %>% # make it a table
  slice(-1) %>% # remove one row
  as_tibble()

table_marj
```



# Star Wars Movie info

I want the data from [here]https://www.imdb.com/list/ls070150896/

```{r}
url = "https://www.imdb.com/list/ls070150896/"

swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
```

Grab elements that I want.

```{r}
title_vec = 
  swm_html %>%
  html_nodes(".lister-item-header a") %>% # use selectorgadget to select this
  html_text() # want only the text

gross_rev_vec = 
  swm_html %>%
  html_nodes(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

runtime_vec = 
  swm_html %>%
  html_nodes(".runtime") %>%
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    rev = gross_rev_vec,
    runtime = runtime_vec)
```

## API csv and JSON 

```{r}
# csv
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% # use the GET to get url
  content("parsed")

# json file
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% # use the GET to get url
  content("text") %>% 
jsonlite::fromJSON() %>% # make it looks like a df
  as_tibble()
```

## BRFESS
```{r}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% # use query parametter, and set the limit to 5000
  content("parsed")
```

